# index:
#     path: /
#     controller: App\Controller\SecurityController::login

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
        controller: App\Controller\SecurityController::login
    type: attribute

# app_homepage:
#     path: /
#     controller: App\Controller\SecurityController::login

